package org.usfirst.frc2337.MotionMagicCommandBasedExample;

import org.usfirst.frc2337.MotionMagicCommandBasedExample.commands.*;
import org.usfirst.frc2337.MotionMagicCommandBasedExample.subsystems.*;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;



/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick joystickDriver;
    
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystickDriver = new Joystick(0);
    	JoystickButton			driver_GreenA			= new JoystickButton(joystickDriver, 1);
    	JoystickButton			driver_RedB				= new JoystickButton(joystickDriver, 2);
    	JoystickButton			driver_BlueX			= new JoystickButton(joystickDriver, 3);
    	JoystickButton			driver_YellowY			= new JoystickButton(joystickDriver, 4);
    	JoystickButton			driver_BumperLeft		= new JoystickButton(joystickDriver, 5);
    	JoystickButton			driver_BumperRight 		= new JoystickButton(joystickDriver, 6);
    	JoystickButton			driver_Back				= new JoystickButton(joystickDriver, 7);
    	JoystickButton			driver_Start			= new JoystickButton(joystickDriver, 8);
    	JoystickButton			driver_LeftStick		= new JoystickButton(joystickDriver, 9);
    	JoystickButton			driver_RightStick		= new JoystickButton(joystickDriver, 10);
        

    	driver_GreenA.whileHeld(new MotionMagic(10));
    	driver_BumperRight.whileHeld(new MotionMagic(Robot.oi.joystickDriver.getRawAxis(1)*(-10)));
    	driver_BumperLeft.whileHeld(new DriveNerdy());
    	


        // SmartDashboard Buttons
        //SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("MotionMagic", new MotionMagic());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystickDriver() {
        return joystickDriver;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

